name: jaat_app
description: A new Flutter project.
publish_to: none
version: 1.0.6+1
environment:
    sdk: '>=2.18.2 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2

    #architecture dependencies
    get_it: ^7.6.0
    logger: ^1.4.0
    stacked: ^3.4.1
    responsive_builder: ^0.7.0
    equatable: ^2.0.5 
    provider: ^6.0.5
    # hive_flutter: ^1.1.0
    # hive: ^2.2.3

    ####bellow are app dependencies####
    http: ^0.13.4
    another_flushbar: ^1.10.29
    shared_preferences: ^2.0.16
    flutter_launcher_icons: ^0.11.0

    #dependency for cheking network connection
    connectivity_plus: ^6.0.5
    intl: ^0.19.0
    url_launcher: ^6.3.0
    url_launcher_ios: ^6.3.1
    shimmer: ^2.0.0
    flutter_html: ^3.0.0-alpha.6
    cached_network_image: ^3.3.1
    flutter_easyloading: ^3.0.5

    #dependency for making functionality like android's onResume() and IOS's viewIsAppearing()
    focus_detector: ^2.0.1 

    #dependency for device id (using it for firebase push notifications to register device on backend)
    platform_device_id: ^1.0.1

    #dependencies for invice pdf download/view
    dio: ^5.0.1
    path_provider: ^2.0.13
    open_file_safe: ^3.2.3

    #dependencies for push notifications
    # firebase_messaging: ^14.3.0
    firebase_core: ^2.7.0
    # awesome_notifications: ^0.7.4+1

    #dependency for deepliking (using for sharing products)
    # firebase_dynamic_links: ^5.3.1

    #dependency for external sharing
    # share_plus: ^4.1.0

    #dependency for webview (its an older version, downgraded due to dependency conflict with flutter html)
    webview_flutter: ^2.0.4
    country_code_picker: ^3.0.0
    dot_navigation_bar: ^1.0.2
    responsive_navigation_bar: ^5.0.0
    image_picker: ^1.0.5
    change_app_package_name: ^1.3.0
    calendar_date_picker2: ^1.1.5
    # agora_chat_sdk: ^1.2.0
    agora_chat_sdk: ^1.3.0-beta.1
    flutter_localization: ^0.2.0
    dotted_border: ^2.1.0
    flutter_svg: ^2.0.9
    flutter_localizations:
        sdk: flutter
    pinput: ^5.0.0
    agora_uikit: ^1.3.10
    fluttertoast: ^8.2.5
    agora_rtm: ^1.5.9
    flutter_image_compress: ^2.3.0
    modal_bottom_sheet: ^3.0.0
    stacked_services: ^1.5.0
    mime: ^1.0.0
    http_parser: ^4.0.2
    currency_picker: ^2.0.21
    csc_picker: ^0.2.7
    internet_connection_checker: ^1.0.0+1
    flutter_typeahead: ^5.2.0
#  flutter_local_notifications: ^8.2.0



dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/logos/logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/logos/logo.png"

flutter:
    generate: true
    uses-material-design: true
    assets:
        - assets/images/
        - assets/logos/
        - assets/fonts/
        - assets/svg/
        - assets/categories.json
        - assets/countries.json



    fonts:
        - family: Urbanist
          fonts:
          - asset: assets/fonts/Urbanist-Regular.ttf
          - asset: assets/fonts/InterTight-Regular.ttf
          - asset: assets/fonts/InterTight-SemiBold.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages